### PR TITLE
Add links to G4 and NEXUS tutorial

### PR DESCRIPTION
**Pull request by paolafer**
This PR adds the links to the slides and recording of the G4&NEXUS tutorials given in 2022.

### CODE REVIEW

**Comment by paolafer** [comment]
@gonzaponte, te he puesto de reviewer, porque creo que es un PR muy sencillo y tenemos que incorporarlo ya (la gente sigue preguntando).

**Review by gonzaponte — APPROVED** [review]
The links are correct, but I can't check that clicking on them works on the online version. Anyway, seems simple enough to believe they will work.

**Comment by paolafer** [comment]
pleeeeease, @halmamol can you approve this PR :-)?

**Review by halmamol — APPROVED** [review]
These tutorials were missing on the documentation webpage and the links are correct. Approved! :D

**Pull request merged**
